GET http://localhost:8080/names

###

GET http://localhost:8080/addToWatchlist?id=65bcef92141e0276818a3ea7

###

GET http://localhost:8080/names/?skip=9000&limit=10

###

GET http://localhost:8080/names?skip=NaN&limit=10&sex=m&prefix=&notPrefix=&suffix=&notSuffix=&syllables=

###

GET http://localhost:8080/names/count?sex=&prefix=&notPrefix=&suffix=&notSuffix=&syllables=
